import { createSlice } from '@reduxjs/toolkit';

// Define the initial state
const initialState = {
  isUserAuthenticated: false,
};

// Create the slice
const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    login: (state) => {
      state.isUserAuthenticated = true;
    },
    logout: (state) => {
      state.isUserAuthenticated = false;
    },
    setIsUserAuthenticated: (state, action) => {
      state.isUserAuthenticated = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { login, logout, setIsUserAuthenticated } = authSlice.actions;

// Export the reducer to be used in the store
export default authSlice.reducer;
