export const BACKEND_BASE_URL = import.meta.env.VITE_BACKEND_URL;
export const STRIPE_PUBLISHABLE_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY;
export const VITE_SERVICE_PROVIDER_EMAIL = import.meta.env.VITE_SERVICE_PROVIDER_EMAIL;